- pom.xml
- src/main/java/org/folio/services/impl/MailServiceImpl.java
Security vulnerability reported in jackson-databind
> FOLIO-1604

- ramls/email_entity.json
- src/main/java/org/folio/services/impl/MailServiceImpl.java
- src/test/java/org/folio/rest/impl/EmailAPITest.java
- src/test/java/org/folio/util/StubUtils.java
>  MODLOGIN-60-FIX

- pom.xml
> MODLOGIN-60 FIX

- pom.xml
- src/main/java/org/folio/rest/impl/EmailAPI.java
- src/main/java/org/folio/services/impl/MailServiceImpl.java
- src/main/java/org/folio/util/EmailUtils.java
- src/test/java/org/folio/rest/impl/EmailAPITest.java
- src/test/java/org/folio/rest/impl/SendingEmailTest.java
- src/test/java/org/folio/util/EmailUtilsTest.java
- src/test/java/org/folio/util/StubUtils.java
**Approach**
- Add additional tests to cover invalid cases
- Add mock server implementation to check message delivery
**Link**
[MODEMAIL-12](https://issues.folio.org/browse/MODEMAIL-12)
> MODEMAIL-12 Increase test coverage for mod-email

- README.md
- ramls/examples/configuration.sample
- src/main/java/org/folio/rest/impl/EmailAPI.java
- src/test/java/org/folio/util/StubUtils.java
Resolves: [MODEMAIL-19](https://issues.folio.org/browse/MODEMAIL-19)
> Rename "SMPT" to "SMTP"

- src/main/java/org/folio/exceptions/ConfigurationException.java
- src/main/java/org/folio/exceptions/SmtpConfigurationException.java
- src/main/java/org/folio/rest/impl/base/AbstractEmail.java
- src/test/java/org/folio/rest/impl/EmailAPITest.java
- src/test/java/org/folio/rest/impl/GettingMetricsTest.java
**Purpose**
Fix response status.
Resolves: [MODEMAIL-24](https://issues.folio.org/browse/MODEMAIL-24)
> MODEMAIL-24 Fix response status of the module

- Dockerfile
- Jenkinsfile
- pom.xml
- src/test/java/org/folio/rest/impl/EmailAPITest.java
- upgrade to jdk 11;
- upgrade RMB to 31.0.2
Resolves: [MODEMAIL-39](https://issues.folio.org/browse/MODEMAIL-39)
> MODEMAIL-39 upgrade RMB to 31.0.2 and jdk11

- pom.xml
Resolves [MODEMAIL-44](https://issues.folio.org/browse/MODEMAIL-44).
> [MODEMAIL-44] Upgrade to RMB 31.1.5 and Vert.x 3.9.4

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/impl/base/AbstractEmail.java
- src/main/java/org/folio/services/email/impl/MailServiceImpl.java
- src/main/java/org/folio/services/storage/impl/StorageServiceImpl.java
- src/test/java/org/folio/rest/impl/base/AbstractAPITest.java
- src/test/resources/log4j2-test.properties
Solves: [MODEMAIL-48](https://issues.folio.org/browse/MODEMAIL-48)
> MODEMAIL-48 Upgrade to RMB v32

- src/main/java/org/folio/services/email/impl/MailServiceImpl.java
- src/test/java/org/folio/rest/impl/SendingEmailTest.java
- src/test/java/org/folio/util/StubUtils.java
**Purpose**
Implement the ability to add arbitrary headers to emails sent via mod-email. For a description of one particular usecase see [UXPROD-2698](https://issues.folio.org/browse/UXPROD-2698).
**Approach**
Custom headers are configured by creating entries in mod-configuration with following (required) properties:
```
{
"module": "SMTP_SERVER",
"configName": "email.headers",
"code": "HEADER_NAME_HERE",
"value": "HEADER_VALUE_HERE"
}
```
Where `HEADER_NAME_HERE` should be replaced with the name of your custom header, e.g. `X-SES-CONFIGURATION-SET`, and `HEADER_VALUE_HERE` should be replaced with desired value.
Values of properties `module` and `configName` should not be changed, and are required in order to be discovered by mod-email and treated as custom header configurations.
You can …
> [MODEMAIL-57] Add support for configurable custom headers

- descriptors/DeploymentDescriptor-template.json
- pom.xml
- src/test/java/org/folio/rest/impl/EmailAPITest.java
- src/test/java/org/folio/rest/impl/base/AbstractAPITest.java
Resolves: [MODEMAIL-58](https://issues.folio.org/browse/MODEMAIL-58)
> MODEMAIL-58 update vertx and rmb versions

- NEWS.md
- pom.xml
Resolves [MODEMAIL-60](https://issues.folio.org/browse/MODEMAIL-60).
> [MODEMAIL-60] Release 1.11.0

- NEWS.md
- pom.xml
Resolves  [MODEMAIL-62](https://issues.folio.org/browse/MODEMAIL-62)
> [MODEMAIL-62] Release 1.12.0

- README.md
- ramls/examples/configuration.sample
- src/test/java/org/folio/util/StubUtils.java
Resolves: [MODEMAIL-65](https://issues.folio.org/browse/MODEMAIL-65)
> MODEMAIL-65 update README

- ramls/email_entity.json
- src/main/java/org/folio/rest/impl/DelayedTasksAPI.java
- src/main/java/org/folio/rest/impl/base/AbstractEmail.java
- src/main/java/org/folio/services/email/impl/MailServiceImpl.java
- src/test/java/org/folio/rest/impl/RetryFailedEmailsTest.java
https://issues.folio.org/browse/MODEMAIL-73
> [MODEMAIL-73] Fix typo: attemptsCount -> attemptCount

- pom.xml
[MODEMAIL-74](https://issues.folio.org/browse/MODEMAIL-74)
_RMB v34 upgrade_
> MODEMAIL-74: RMB v34 upgrade

- pom.xml
[MODEMAIL-78](https://issues.folio.org/browse/MODEMAIL-78)
> [MODEMAIL-78] Upgrade to RMB 35.0.0 and Vertx 4.3.3

- README.md
Part of [MODEMAIL-84](https://issues.folio.org/browse/MODEMAIL-84)
Update README.md to reflect new approach to SMTP configuration
> MODEMAIL-76 Update README.md

- NEWS.md
- README.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/examples/smtp-configuration.sample
- ramls/examples/smtp-configurations.sample
- ramls/smtp-configuration.json
- ramls/smtp-configuration.raml
- ramls/smtp-configurations.json
- src/main/java/org/folio/exceptions/FailedToCreateRepositoryException.java
- src/main/java/org/folio/exceptions/SmtpConfigurationNotFoundException.java
- src/main/java/org/folio/repository/BaseRepository.java
- src/main/java/org/folio/repository/SmtpConfigurationRepository.java
- src/main/java/org/folio/rest/client/OkapiClient.java
- src/main/java/org/folio/rest/client/WebClientProvider.java
- src/main/java/org/folio/rest/impl/SmtpConfigurationApi.java
- src/main/java/org/folio/rest/impl/base/AbstractEmail.java
- src/main/java/org/folio/services/SmtpConfigurationService.java
- src/main/java/org/folio/services/email/impl/MailServiceImpl.java
- src/main/java/org/folio/util/EmailUtils.java
- src/main/resources/templates/db_scripts/addOneRowConstraintToSmtpConfiguration.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/matchers/JsonMatchers.java
- src/test/java/org/folio/rest/impl/EmailAPITest.java
- src/test/java/org/folio/rest/impl/MailConfigTest.java
- src/test/java/org/folio/rest/impl/RetryFailedEmailsTest.java
- src/test/java/org/folio/rest/impl/SendingEmailTest.java
- src/test/java/org/folio/rest/impl/SmtpConfigurationTest.java
- src/test/java/org/folio/rest/impl/base/AbstractAPITest.java
- src/test/java/org/folio/util/StubUtils.java
Resolves: [MODEMAIL-85](https://issues.folio.org/browse/MODEMAIL-85)
> [MODEMAIL-85] Release v1.15.1

- src/main/resources/templates/db_scripts/schema.json
Resolves [MODEMAIL-86](https://issues.folio.org/browse/MODEMAIL-86)
> MODEMAIL-86 Change fromModuleVersion to 1.15.2 for smtp_configuration

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
Resolves: [MODEMAIL-87](https://issues.folio.org/browse/MODEMAIL-87)
> [MODEMAIL-86] Release v1.15.2

- PULL_REQUEST_TEMPLATE.md
- src/main/resources/log4j2-json.properties
- src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODEMAIL-90
> MODEMAIL-90: Logging improvement - check log4j configuration

- README.md
See https://github.com/folio-org/mod-email/pull/85#pullrequestreview-1194932424
> Fix README section Goal

- NEWS.md
- pom.xml
> Tmp release 1.17.0

- pom.xml
- src/test/java/org/folio/rest/impl/base/AbstractAPITest.java
- src/test/java/org/folio/util/StubUtils.java
> MODEMAIL-99 - Upgrade RMB version to 35.3.0

- .github/workflows/postgres.yml
- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODEMAIL-101
> MODEMAIL-101: Ramsons release

- src/main/java/org/folio/rest/impl/DelayedTasksAPI.java
- src/main/java/org/folio/rest/impl/base/AbstractEmail.java
Address the PII issue reported in the Jira. Changed the log type.
Before -- 
After --
> [MODEMAIL-104] - Change the log levels based on PII issue.

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/DelayedTasksAPI.java
- src/main/java/org/folio/rest/impl/base/AbstractEmail.java
> To release 1.18.1

- .github/workflows/postgres.yml
- Dockerfile
- Jenkinsfile
- pom.xml
> Folio-4225 - Java and RMB version upgrade
